export type Coordinates = [number, number];
export type Intent = 'Discover something new' | 'Go deeper on history' | 'Art & culture' | 'Weird stories' | 'Local life' | 'Surprise me';
export type Discovery = {
  id: string; title: string; subtitle: string; location: string; coordinates: Coordinates;
  minutes: number; hook: string; story: string; why: string; themes: string[];
  intentAffinity: Partial<Record<Intent, number>>; score: { relevance: number; novelty: number; visual: number };
  visualDirection: string; color: string; image?: string;
};

export const startingPoint: Coordinates = [41.3831, 2.1768];

export const discoveries: Discovery[] = [
  { id: 'bishop-bridge', title: 'A bridge built to feel ancient', subtitle: 'A beautiful little architectural lie.', location: 'Pont del Bisbe', coordinates: [41.3832, 2.1761], minutes: 2, hook: 'Here is a beautiful fake.', story: 'This is one of Barcelona’s most photographed Gothic details. It looks medieval, but it was built in 1928. Underneath hangs a skull pierced by a dagger; local superstition says Barcelona will fall if it is removed.', why: 'It is two minutes away, immediately visual, and flips an assumption almost everyone makes.', themes: ['weird stories', 'architecture', 'hidden histories'], intentAffinity: { 'Weird stories': 99, 'Discover something new': 95, 'Surprise me': 94, 'Art & culture': 78 }, score: { relevance: 90, novelty: 98, visual: 99 }, visualDirection: 'Looking steeply upward inside a very narrow stone-paved medieval alley in Barcelona’s Gothic Quarter: an ornate neo-Gothic enclosed covered footbridge spans high overhead between two tall pale limestone facades, only a metre or two of sky visible either side of it. The little bridge is a single short enclosed walkway with delicate lace-like carved stone tracery, crocketed pinnacles and one small pointed-arch window; a carved skull pierced by a dagger hangs from its underside. Blue-hour light falls into the slot of the alley, warm lamplight on the stone. Strictly no water, no river, no canal, no wide road, no traffic, no iron or steel truss, not a long viaduct — a short decorative skywalk between two buildings in a pedestrian lane. Vertical mobile composition, no text.', color: '#6c6558' },
  { id: 'felip-neri', title: 'The wall that remembers', subtitle: 'Look closer at the scars.', location: 'Plaça de Sant Felip Neri', coordinates: [41.3837, 2.1773], minutes: 3, hook: 'Okay, slow down.', story: 'The marks in this wall are not medieval. A bomb hit this small square during the Spanish Civil War. The plaque tells one version; the people who lived around it tell a more complicated one.', why: 'It turns an ordinary-looking wall into a story and is a quiet counterpoint to the Gothic Quarter’s postcard beauty.', themes: ['civil war', 'hidden histories', 'architecture'], intentAffinity: { 'Go deeper on history': 99, 'Discover something new': 92, 'Surprise me': 91, 'Weird stories': 82 }, score: { relevance: 98, novelty: 94, visual: 91 }, visualDirection: 'A pale limestone church wall in a small enclosed Barcelona square, seen straight on in warm low late-afternoon sunlight. The wall is completely intact and structurally sound, but its entire surface is finely peppered with thousands of shallow chips and pits no bigger than a coin, spattered across the stone like buckshot, each tiny pockmark casting its own hard little shadow in the raking light. A plain baroque doorway and a small rose window sit within the peppered stone. At the lower edge of the frame, a low octagonal stone fountain and worn paving. A single person stands close to the wall, one hand raised near the pitted surface. Restrained documentary realism, quiet and still. Vertical mobile composition, no text.', color: '#d86843' },
  { id: 'temple-augustus', title: 'Four Roman columns hiding in plain sight', subtitle: 'The oldest room in the Gothic Quarter.', location: 'Temple of Augustus', coordinates: [41.3827, 2.1765], minutes: 3, hook: 'There is a Roman temple inside this medieval alley.', story: 'Behind an almost invisible doorway, four towering columns from the Roman Temple of Augustus survive inside a tight courtyard. The city literally built its medieval heart around them.', why: 'It is a major historical reveal with almost no visual announcement from the street.', themes: ['roman barcelona', 'history', 'architecture'], intentAffinity: { 'Go deeper on history': 97, 'Discover something new': 91, 'Art & culture': 80, 'Surprise me': 88 }, score: { relevance: 94, novelty: 95, visual: 94 }, visualDirection: 'Four immense freestanding fluted Roman Corinthian columns, nine metres tall with ornate acanthus capitals, crammed inside a tiny medieval courtyard barely wider than the columns themselves, a later stone building constructed tightly around them with plain plastered walls and a high wooden beamed ceiling. A single visitor stands at their base looking up, dwarfed by the scale. A dramatic shaft of daylight rakes across warm limestone. Strictly an enclosed interior courtyard: not a temple portico, not a long colonnade of many columns, no open plaza, no ruins in a landscape, no sky-filled panorama. Vertical mobile composition, no text.', color: '#ac7752' },
  { id: 'call', title: 'A street the city tried to erase', subtitle: 'A memory held in the stones.', location: 'El Call — old Jewish quarter', coordinates: [41.3829, 2.1765], minutes: 4, hook: 'This alley holds another Barcelona.', story: 'These narrow lanes were once the centre of Barcelona’s Jewish community. The community was violently displaced in 1391, but fragments remain in the stones, names and thresholds if you know where to look.', why: 'It directly connects to the stories around it, is extremely close, and most visitors walk past without realising what this street held.', themes: ['hidden histories', 'medieval barcelona', 'jewish heritage'], intentAffinity: { 'Go deeper on history': 96, 'Discover something new': 96, 'Surprise me': 96, 'Weird stories': 87 }, score: { relevance: 97, novelty: 96, visual: 87 }, visualDirection: 'An atmospheric view through a narrow Gothic Quarter lane at blue hour, subtle traces of a vanished Jewish neighbourhood appearing as layers of memory in stone, cinematic but historically respectful, no text.', color: '#355d51' },
  { id: 'picasso', title: 'The artist’s teenage Barcelona', subtitle: 'Before the blue period, before Paris.', location: 'Museu Picasso', coordinates: [41.3852, 2.1802], minutes: 7, hook: 'Picasso arrived here before he was Picasso.', story: 'Barcelona was where a teenage Picasso learned to look. The museum sits in a set of medieval palaces, making the route from old stone streets to modern art feel almost accidental.', why: 'It gives an art-focused walk a human origin story instead of a museum checklist.', themes: ['art', 'culture', 'modernism'], intentAffinity: { 'Art & culture': 99, 'Discover something new': 78, 'Surprise me': 79 }, score: { relevance: 98, novelty: 84, visual: 93 }, visualDirection: 'Young artist sketching in a grand medieval Barcelona palace courtyard, contemporary editorial photography blended with loose blue charcoal studies, sophisticated art-book feel, vertical, no text.', color: '#496f86' },
  { id: 'quatre-gats', title: 'Where modern Barcelona learned to be weird', subtitle: 'A café that became a cultural switchboard.', location: 'Els Quatre Gats', coordinates: [41.3854, 2.1757], minutes: 5, hook: 'This was a café, but really it was a conspiracy.', story: 'Els Quatre Gats was where artists, writers and troublemakers gathered at the turn of the twentieth century. It helped make modernism feel like a social scene rather than an art movement.', why: 'It is a perfect art-and-culture stop because the story is social, messy and alive.', themes: ['art', 'culture', 'local life'], intentAffinity: { 'Art & culture': 95, 'Local life': 86, 'Weird stories': 79, 'Surprise me': 82 }, score: { relevance: 93, novelty: 88, visual: 90 }, visualDirection: 'The interior of a turn-of-the-century Barcelona modernista tavern in 1900: warm dark wood panelling, wrought-iron fittings, patterned ceramic floor tiles, small marble-topped tables and bentwood chairs, oil lamps and candles, framed paintings hung close together across the walls. A dozen artists, writers and bohemians in 1900 dress — high collars, waistcoats, long skirts — leaning in over drinks in animated conversation. Candlelight, tactile film grain, period editorial photography. Strictly an indoor scene: no outdoor terrace, no street, no pavement dining, no modern clothing, no contemporary people. Vertical mobile composition, no text.', color: '#9a6748' },
  { id: 'sant-jaume', title: 'The square where Barcelona argues with itself', subtitle: 'Power, protest, and everyday civic life.', location: 'Plaça de Sant Jaume', coordinates: [41.3829, 2.1768], minutes: 1, hook: 'This is Barcelona’s living room.', story: 'Plaça de Sant Jaume faces both the city hall and the Catalan government. On an ordinary day it is a crossing point; on an important day it is where the city turns up to be heard.', why: 'It makes local life tangible: not a monument, but a square that still has a job to do.', themes: ['local life', 'civic life', 'catalan identity'], intentAffinity: { 'Local life': 99, 'Discover something new': 76, 'Surprise me': 78 }, score: { relevance: 96, novelty: 80, visual: 83 }, visualDirection: 'A small, tightly enclosed rectangular civic square in Barcelona’s Gothic Quarter at dusk, framed narrowly at eye level from one corner so the square reads as compact and everyday. Filling the frame ahead, the flat stone facade of a neoclassical town hall with four shallow pilasters and a plain triangular pediment above its door; close on the left, the flat Renaissance facade of a government palace with one carved stone balcony over its arched doorway. The two facades face each other across plain grey stone paving. A handful of residents cross on foot, one pausing to talk, warm lit windows against a deep blue evening sky. Quiet documentary travel photography, ordinary and unglamorous. Vertical mobile composition, no text.', color: '#465d73' },
];
