import { useEffect, useRef } from 'react';
import L from 'leaflet';
import type { Coordinates, Discovery } from './data';

export function TourMap({ from, to, route, stops = [], activeIndex = 0, compact = false, full = false }: { from: Coordinates; to: Coordinates; route?: Coordinates[]; stops?: Discovery[]; activeIndex?: number; compact?: boolean; full?: boolean }) {
  const element = useRef<HTMLDivElement | null>(null); const mapRef = useRef<L.Map | null>(null); const group = useRef<L.LayerGroup | null>(null);
  useEffect(() => { if (!element.current || mapRef.current) return; const map = L.map(element.current, { zoomControl: false, attributionControl: true, dragging: !compact, scrollWheelZoom: !compact }).setView(from, 16); L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { attribution: '© OpenStreetMap contributors', maxZoom: 19 }).addTo(map); L.control.zoom({ position: 'bottomright' }).addTo(map); mapRef.current = map; return () => { map.remove(); mapRef.current = null; }; }, [compact, from]);
  useEffect(() => { const map = mapRef.current; if (!map) return; group.current?.remove(); const layers = L.layerGroup().addTo(map); group.current = layers; const points = route?.length ? route : [from, to]; L.polyline(points, { color: '#ee6941', weight: 5, opacity: .96, dashArray: route ? undefined : '8 7' }).addTo(layers); const dot = (color: string, size: number, label?: string) => L.divIcon({ className: 'map-dot-wrap', html: `<span class="map-dot ${label ? 'numbered' : ''}" style="--dot:${color};--size:${size}px">${label ?? ''}</span>`, iconSize: [size, size], iconAnchor: [size / 2, size / 2] }); L.marker(from, { icon: dot('#11251d', 16) }).addTo(layers); if (stops.length) { stops.forEach((stop, index) => L.marker(stop.coordinates, { icon: dot(index === activeIndex ? '#ee6941' : '#f8f2e8', index === activeIndex ? 30 : 24, String(index + 1)) }).addTo(layers)); } else L.marker(to, { icon: dot('#ee6941', 24) }).addTo(layers); const bounds = L.latLngBounds([...points, ...stops.map(stop => stop.coordinates)]); map.fitBounds(bounds, { padding: compact ? [25, 25] : [45, 45], maxZoom: 17 }); }, [from, to, route, stops, activeIndex, compact]);
  return <div className={compact ? 'tour-map compact-map' : full ? 'tour-map full-map' : 'tour-map'} ref={element} />;
}
